[package]
name = "lucyrs"
version = "0.1.0"
authors = ["mfehr <mathieu.fehr@gmail.com>"]
edition = "2018"

[build]
build = "build.rs"

[build-dependencies]
lalrpop = "0.16.1"

[dependencies]
lalrpop-util = "0.16.1"
regex = "0.2.1"
petgraph = "0.4.13"